// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdulyYa2zubItSwKdeJ766_XxxG0K6GkA',
    appId: '1:553020657135:web:82c21ea574e106fad03a1a',
    messagingSenderId: '553020657135',
    projectId: 'im-doing-mybest',
    authDomain: 'im-doing-mybest.firebaseapp.com',
    storageBucket: 'im-doing-mybest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ZMWrDMcyIfhCENcybiYNtJQ3SzsUIKs',
    appId: '1:553020657135:android:178c65ba572ff370d03a1a',
    messagingSenderId: '553020657135',
    projectId: 'im-doing-mybest',
    storageBucket: 'im-doing-mybest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjD-yRI6O5OmkwIB4VERarmWfr8uFKfUk',
    appId: '1:553020657135:ios:794ef131624f0182d03a1a',
    messagingSenderId: '553020657135',
    projectId: 'im-doing-mybest',
    storageBucket: 'im-doing-mybest.appspot.com',
    iosClientId: '553020657135-gtds2l84eomc4d7bodss81kal1rh74sn.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mypersonalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjD-yRI6O5OmkwIB4VERarmWfr8uFKfUk',
    appId: '1:553020657135:ios:fccb31cb35c67d21d03a1a',
    messagingSenderId: '553020657135',
    projectId: 'im-doing-mybest',
    storageBucket: 'im-doing-mybest.appspot.com',
    iosClientId: '553020657135-rgth62jk45692b36psu14t8ll6i6v8qr.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuffup.mypersonalnotes.RunnerTests',
  );
}
